/**
 * Copyright (c) 2019-2021 August
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

const { existsSync } = require('fs');
const { version } = require('../package.json');
const { join } = require('path');
const typedoc = require('typedoc');

const log = (message) => process.stdout.write(`[docs] ${message}\n`);

async function generate() {
  log('initalising typedoc...');
  const app = new typedoc.Application();
  app.options.addReader(new typedoc.TSConfigReader());
  app.options.addReader(new typedoc.TypeDocReader());

  app.bootstrap({
    entryPoints: ['src'],
    excludePrivate: true,
    excludeProtected: true
  });

  log('bootstrapped project, now getting reflections');
  const project = app.convert();
  if (project) {
    log('received reflections, now outputing it to scripts/generated/docs.json');

    const outputDir = join(__dirname, 'generated');
    await app.generateJson(project, join(outputDir, 'docs.json'));
  }
}

async function main() {
  if (!existsSync(join(__dirname, 'generated', 'docs.json'))) await generate();

  log('now reading contents...');
  const docs = require(join(__dirname, 'generated', 'docs.json'));
  let elements = [];

  const starting = [
    '-- DO NOT EDIT THIS FILE YOURSELF, THIS IS AUTO-GENERATED --',
    '',
    `Library Version: ${version}`,
    `Updated At: ${new Date().toLocaleString()}`
  ];

  log(`loaded documentation for ${docs.name} and received ${docs.children.length} children to read from`);
  for (let i = 0; i < docs.children.length; i++) {
    const parent = docs.children[i];
    const E = read(parent);

    elements = elements.concat(E);
  }
}

function read(child) {
  const elements = [];

  //console.log(`received ${child.kindString} ${child.name}`);
  if (child.children && child.children.length > 0) {
    for (let i = 0; i < child.children.length; i++) {
      const c = child.children[i];
      console.log(`received ${c.kindString} ${c.name}`);

      elements.push(readChild(c, child));
    }
  }

  return elements;
}

function readChild(child, parent) {
  const elements = {
    parent: parent ? { kind: parent.kindString, name: parent.name } : null,
    constructor: null,
    methods: [],
    accessors: [],
    properties: [],
    variables: [],
    functions: []
  };

  switch (child.kindString) {
    case 'Class': {
      // noop
    } break;

    case 'Method': {
      // noop
    } break;

    case 'Accessor': {
      // noop
    } break;

    case 'Property': {
      // noop
    } break;

    case 'Variable': {
      // noop
    } break;

    case 'Function': {
      // noop
    } break;

    case 'Constructor': {
      // noop
    } break;
  }

  return elements;
}

main();
