name: ESLint
on:
  push:
    branches:
      - master
    paths-ignore:
      # We ignore node modules, the build that TypeScript creates and the root directory
      # because it's mostly modifying the source code, not really these folder/files
      - 'node_modules/**'
      - 'build/**'
      - '.eslintrc.json'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
      - 'tsconfig.json'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only build from Node v10+
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g eslint jest
      - run: npm i
      - run: eslint src --ext .ts --fix
      - run: yarn test